name: Deploy to Render on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Serve React App Locally
        run: |
          npm install -g serve
          serve -s build &
          sleep 3 # Wait for the server to start

      - name: Run Tests (if available)
        run: npm test || true

      - name: Verify App Is Working
        run: |
          curl http://localhost:5000  # Adjust the port if needed

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -d "branch=${{ github.head_ref }}"
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
